<a href="https://colab.research.google.com/github/sayaliKutwal/101-NumPy-Exercises-for-Data-Analysis-/blob/master/Exercises_1_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Website for exercises https://www.machinelearningplus.com/python/101-numpy-exercises-python/

# 1.Import numpy as np and see the version

Difficulty Level: L1

Q. Import numpy as np and print the version number.

In [0]:
import numpy as np
print(np.__version__)


1.16.5


# 2.How to create a 1D array?

Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output:
> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [0]:
zero_to_10 = np.arange(0, 10)
zero_to_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3.How to create a boolean array?

Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [0]:
# method 1
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

More about numpy.full() https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html

In [0]:
# Method 2
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

More about numpy.ones https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html 

# 4.How to extract items that satisfy a given condition from 1D array?

Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

> array([1, 3, 5, 7, 9])

In [0]:
input = np.arange(0, 10)
output = input[input % 2 == 1]
output

array([1, 3, 5, 7, 9])

# 5.How to replace items that satisfy a condition with another value in numpy array?

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [0]:
input = np.arange(0, 10)
input[input % 2 == 1] = -1
input

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6.How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
out
>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr
>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
input = np.arange(10)
out = np.where(input % 2 == 1, -1, input)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

More about numpy.where() https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html 

# 7.How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

> array([[0, 1, 2, 3, 4],
>        [5, 6, 7, 8, 9]])

In [0]:
input = np.arange(10)
input.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

More about numpy.reshape() https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

8.How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

> array([[0, 1, 2, 3, 4],
>        [5, 6, 7, 8, 9],
>        [1, 1, 1, 1, 1],
>        [1, 1, 1, 1, 1]])

In [0]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
